# Makefile for prcm config app

APP_NAME = prcm_config_app

SRCDIR = $(PLATFORM)
INCDIR = $(PLATFORM) 

# List all the external components/interfaces, whose interface header files 
#  need to be included for this component
INCLUDE_EXERNAL_INTERFACES = 

# List of all external libraries that need to be linked
EXTLIBS_a8host = 

# List all the components required by the application
COMP_LIST_a8host = 

# Common source files and CFLAGS across all platforms and cores
SRCS_COMMON = prcm_config_app.c
CFLAGS_LOCAL_COMMON = -D_LOCAL_CORE_a8host_

# Include common make files
include $(ROOTDIR)/makerules/common.mk

# Nothing beyond this point
